version: '3'
services:
  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: password
    ports:
        - "4306:4306"
    volumes:
        - ./db/mysql/volumes:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db