version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./public:/usr/share/nginx/public:cached
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: 
      context: .
      dockerfile: Dockerfile_production
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app:cached
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file: development.env
    environment:
      RAILS_ENV: production
  db:
    image: mysql:5.7.27
    volumes:
      - db-volume:/var/lib/mysql
    env_file: development.env
    # environment:
    #   MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
volumes:
  db-volume: