version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: tandahq/circleci-ruby:2.7.3-stretch-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - run:  gem install bundler:2.1.4
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
